# mybatis setting
mybatis:
  mapper-locations: xml/**/*.xml
                  #???/**/*.xml
spring:
  application:
    name: GreenGramVar1
  # DB setting
  datasource:
    url: jdbc:mariadb://localhost/greengram_ver1
    username: root
    password: green502

springdoc:

  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    operations-sorter: method
    path: /swagger
